name: Update GeoJSON

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch GeoJSON from Google Apps Script
        run: |
          curl -s "https://script.google.com/macros/s/YOUR_DEPLOYMENT_ID/exec" -o offices.geojson
          ls -lh offices.geojson

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add offices.geojson
          git commit -m "Update offices.geojson [skip ci]" || echo "No changes to commit"
          git push
