name: Update GeoJSON

on:
  schedule:
    - cron: "0 * * * *"   # every hour; adjust as needed
  workflow_dispatch:       # lets you trigger manually in Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest GeoJSON
        run: |
          curl -s "https://script.google.com/macros/s/AKfycbxImoosV5mh05LmYJhrvB-Z9EQ97HcublGuH683gYXg2W2Mden6tJ6j9-RP6puMyU6D/exec" \
          -o offices.geojson

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add offices.geojson
          git diff --cached --quiet || git commit -m "Update offices.geojson [skip ci]"
          git push
